### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by livhong** [twz915/django-minicms#1]
在views.py中
python3中没有urllib.basejoin模块，可替换为urllib.parse.urljoin

在utils.py中
def size(self):
        return self.size

```
@size.setter
def size(self, newsize):
    try:
        self.size = long(newsize)
    except:
        self.size = 0
```

该部分代码会造成死循环
可以直接注释掉

**Comment by twz915** [comment]
该问题已经修复，目前 提供的 DjangoUeditor3 应该是可用的
